jwt:
  secretKey: Q05VLUxJS0UtTElPTi1BUFBMSUNBVElPTi1TRUNSRVQtS0VZ  #CNU-LIKE-LION-APPLICATION-SECRET-KEY 를 base 64로 인코딩한 값
  accessTokenExpirationDay: 100 # 100일로 설정
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    hibernate:
      ddl-auto: create
